### ISSUE TITLE
Unit testing not working

### ISSUE THREAD

**Issue by MbDiop** [tdayris-perso/rna-count-salmon#1]
I followed the wiki to perform unit tests : "Scripts embedded within this pipeline can be tested with pytest. Go within the tests sub-directory and run: `make all-unit-tests`".

The error returned is : `make: *** Aucune règle pour fabriquer la cible « all-unit-tests ». Arrêt.`

There is no makefile in the tests sub-directory.

**Comment by aoumess** [comment]
Actually this is a typo : the makefile is in the root dir, so one should just remove the "Go within the tests sub-directory and" wiki part.

**Comment by tdayris-perso** [comment]
Wiki mis à jour.
Merci!

**Comment by MbDiop** [comment]
I'm working on the cluster and it doesn't work. The `make` command was executed in the root directory that contains the Makefile. 

```
(rna-count-salmon) [user@flamingo rna-count-salmon]$ make all-unit-tests
source $(conda info --base)/etc/profile.d/conda.sh ; conda activate ; conda activate rna-count-salmon && \
pytest -vv scripts/prepare_config.py scripts/prepare_design.py scripts/common_script_rna_count_salmon.py
bash: ligne 0 : bash: source $(conda info --base)/etc/profile.d/conda.sh ; conda activate ; conda activate rna-count-salmon && \
pytest -vv scripts/prepare_config.py scripts/prepare_design.py scripts/common_script_rna_count_salmon.py : nom d'option non valable
make: *** [all-unit-tests] Erreur 2
