### ISSUE TITLE
snakemake option error (--singularity)

### ISSUE THREAD

**Issue by MbDiop** [tdayris-perso/rna-count-salmon#4]
The pipeline has been launched on a slurm cluster with the command line specified here in the documentation : https://github.com/tdayris-perso/rna-count-salmon/wiki/Usage#slurm .
The following error occurred :
`snakemake: error: ambiguous option: --singularity could match --singularity-prefix, --singularity-args`

**Comment by tdayris-perso** [comment]
Documentation mise à jour. Erreur Snakemake et pas liée au pipeline.

https://snakemake.readthedocs.io/en/stable/executing/cli.html#SINGULARITY
