### ISSUE TITLE
snakemake option :  --restart-times has no effect with slurm time limit error

### ISSUE THREAD

**Issue by MbDiop** [tdayris-perso/rna-count-salmon#8]
I'm using this command to launch the pipeline 
```
snakemake --cluster " sbatch --mem={resources.mem_mb}M --cpus-per-task={threads} --time={resources.time_min} " --use-conda --use-singularity --reason --printshellcmds --jobs 20  --restart-times 3

12 of my 16 samples failed due to slurm time limit error.

The snakemake processus never stop and new analysis with more time allocated are never launched.

**Comment by tdayris-perso** [comment]
Completely normal. You do not use profiles, thus the error returned by slurm is not catched due to missing sigterm signal.

Use [slurm](https://github.com/tdayris-perso/slurm) to avoid this in the future.

The error does not come from the pipeline, rather than IGR's slurm configuration.
